version: "3"

services:
  mainflux-counter-run:
    image: mainflux-counter-image
    container_name: mainflux-counter-run
    restart: on-failure
    build: .
    command: go run messages.go
    volumes:
      - ./src:/go/src/app
    working_dir: /go/src/app
    environment:
      PORT: 8915
      DEV1READ1: 
      DEV1READ2: 
      DEVICE1: 
      ADDR: 
    ports:
      - 8915:8915
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8915"]
      interval: 3m
      timeout: 30s
      retries: 3

