version: "3"

services:
  edgex-msg-count:
    image: edgex-msg-count-image
    container_name: edgex-msg-count
    restart: on-failure
    build: .
    command: go run messages.go
    volumes:
      - ./src:/go/src/app
    working_dir: /go/src/app
    environment:
      PORT: 8925
      READING1: 
      READING2: 
      DEVICE: 
      READING_REQUEST1: 
      READING_REQUEST2: 
      EVENT_REQUEST: 
    ports:
      - 8925:8925
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8925"]
      interval: 3m
      timeout: 30s
      retries: 3